### ISSUE TITLE
 no pop-up window

### ISSUE THREAD

**Issue by carppond** [evilpenguin/MachoDecrypt#1]
I installed deb, but there is no pop-up window after starting the software

**Comment by evilpenguin** [comment]
What iOS and what app?

**Comment by carppond** [comment]
Currently I have Taobao popping up prompts, while Douyin and Youku have not popped up.

**Comment by carppond** [comment]
I have another question, why is the decrypted file so big.

**Comment by evilpenguin** [comment]
> Currently I have Taobao popping up prompts, while Douyin and Youku have not popped up.

I released a new deb with changes. Try that.

**Comment by evilpenguin** [comment]
> I have another question, why is the decrypted file so big.

There might be a bug when Im writing to the executable. Whats the size difference?

**Comment by carppond** [comment]
> > Currently I have Taobao popping up prompts, while Douyin and Youku have not popped up.
> 
> I released a new deb with changes. Try that.

After installing the new deb, this issue was resolved.

**Comment by carppond** [comment]
> > I have another question, why is the decrypted file so big.
> 
> There might be a bug when Im writing to the executable. Whats the size difference?

About 1.7G, [image](http://three.objccf.com/WX20201128-105037.png).
ipa is about 150M.

**Comment by carppond** [comment]
> > 目前有淘宝弹出提示，抖音和优酷都没有弹出。
> 
> 我发布了一个新的带有变化的deb。试试看。

**Comment by evilpenguin** [comment]
> > > I have another question, why is the decrypted file so big.
> 
> > 
> 
> > There might be a bug when Im writing to the executable. Whats the size difference?
> 
> 
> 
> About 1.7G, [image](http://three.objccf.com/WX20201128-105037.png).
> 
> ipa is about 150M.

Please open a new issue. Add all the information there, and file sizes.
